### ISSUE TITLE
Correct Datasheet?

### ISSUE THREAD

**Issue by fatdollar** [MightyQ/Qduino_Mini#1]
I was looking at the schematic and noticed that the included datasheet for the fuel gauge is for the MAX17043/MAX17044.  In the schematic however, it is using a MAX17048.

The 2 datasheets are similar but not exactly the same.  I could just be a little bit too worried but I thought I'd mention this in case it was a real issue.

Edit:  I just saw in the readme it says the MAX17048 is used.  I replaced the datasheet in my fork and could do a pull request but it's not much to warrant a pull request I think.

**Comment by MightyQ** [comment]
Great catch, I will correct this right now

**Comment by fatdollar** [comment]
Sounds great!!
